added-delete
zeet-dev/cli pull request #8
Opened 2022-07-13 17:14 UTC by mlyoung25

2022-07-14 17:32 UTC, zzh8829 requested changes

2022-07-14 17:32 UTC, zzh8829 commented on pkg/cmd/delete.go
> +test
remove the word "test"

2022-07-14 17:32 UTC, zzh8829 commented on pkg/api/repo.go
> +func (c *Client) DeleteRepo(ctx context.Context, repoID uuid.UUID, branch string) error {
the branch variable is not needed anymore

2022-07-14 22:04 UTC, mlyoung25 commented
idk what to do but i fixed the requests

2022-07-15 21:48 UTC, merged

2022-07-15 21:48 UTC, zzh8829 commented
👍 nice